# Generated by Django 2.1.5 on 2020-04-21 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.IntegerField(default=-1)),
                ('y_coord', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ['game', 'player', 'x_coord', 'y_coord'],
            },
        ),
        migrations.AlterField(
            model_name='multiplayergame',
            name='game_winner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='api.MinesweeperUser'),
        ),
        migrations.AddField(
            model_name='multiplayercoordinates',
            name='game',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='api.MultiplayerGame'),
        ),
        migrations.AddField(
            model_name='multiplayercoordinates',
            name='player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='api.MinesweeperUser'),
        ),
        migrations.AlterUniqueTogether(
            name='multiplayercoordinates',
            unique_together={('game', 'player', 'x_coord', 'y_coord')},
        ),
    ]
