# Generated by Django 2.1.5 on 2020-04-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplayergame',
            name='game_code',
            field=models.CharField(default='WRONG', max_length=45, unique=True),
        ),
    ]
