# Generated by Django 2.1.5 on 2020-04-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweepergame',
            name='game_time',
            field=models.IntegerField(),
        ),
    ]
