# Generated by Django 2.1.5 on 2020-04-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweeperuser',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
