# Generated by Django 3.0.5 on 2020-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200415_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweeperuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
