# Generated by Django 3.0.5 on 2020-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200415_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweepergame',
            name='difficulty',
            field=models.CharField(default='easy', max_length=45),
        ),
    ]
