# Generated by Django 2.1.5 on 2020-04-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_spectatedcoordinates_opened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spectatedcoordinates',
            options={'ordering': ['game']},
        ),
        migrations.AlterModelOptions(
            name='spectatedgame',
            options={'ordering': ['date']},
        ),
    ]
