# Generated by Django 2.1.5 on 2020-04-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_multiplayercoordinates_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplayergame',
            name='game_winner_time',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='multiplayergame',
            name='gameover',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
