# Generated by Django 2.1.5 on 2020-04-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_minesweepergame_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweeperuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='minesweeperuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
