# Generated by Django 2.1.5 on 2020-05-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_spectatedcoordinates_gameover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spectatedcoordinates',
            options={'ordering': ['game', 'gameover']},
        ),
        migrations.AlterModelOptions(
            name='spectatedgame',
            options={'ordering': ['user', 'date']},
        ),
    ]
